# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.1.0
#
# DESCRIPTION:
#   alacritty TOML configuration file format - https://alacritty.org/config-alacritty.html

# EXAMPLES:
#   alacritty --title "Alacritty Test Terminal"
#   alacritty --title "Alacritty Test Terminal" --command tmux &
#   alacritty --title "Alacritty Test Terminal" --command cat /dev/urandom &
#   alacritty --title "Alacritty Test Terminal" --option 'font.size=9.0' --option 'window.dimensions.columns=200' --option 'window.dimensions.lines=60' --command nvim ~/.config/alacritty/alacritty.toml
#


[general]
import = [                                                # import additional configuration files, imports are loaded in order, skipping all missing files, with the importing file being loaded last, if a field is already present in a previous import, it will be replaced
  "~/.config/alacritty/config-base.toml",                 # config for common parameters - see https://alacritty.org/config-alacritty.html
  #"~/.config/alacritty/config-keybindings.toml",         # config for key bindings -  see https://alacritty.org/config-alacritty.html
  "~/.config/alacritty/config-color-palette.toml",        # color palette - see github catppuccin/alacritty - https://github.com/catppuccin/alacritty
]

